import type { MetadataRoute } from 'next';

/**
 * robots.txt — generated by Next.js from this file at /robots.txt.
 * Allow all crawlers across the public site. Per-page metadata
 * (e.g. /terms and /privacy have `robots: { index: false }`)
 * controls indexing on a route-by-route basis.
 */
export default function robots(): MetadataRoute.Robots {
  const base = 'https://kashkit.us';
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
      },
    ],
    sitemap: `${base}/sitemap.xml`,
    host: base,
  };
}
