import type { MetadataRoute } from 'next';

/**
 * sitemap.xml — generated by Next.js at /sitemap.xml.
 * Only public, indexable routes are listed.
 * /terms and /privacy are deliberately excluded (DRAFT, noindex in their
 * per-page metadata). /occc-notice is required public regulator info, so
 * it stays indexable.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://kashkit.us';
  const now = new Date();

  return [
    {
      url: `${base}/`,
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 1.0,
    },
    {
      url: `${base}/about`,
      lastModified: now,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: `${base}/occc-notice`,
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.4,
    },
  ];
}
